{
 "title": "DashBoard Mining",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mine Duration vs GoTo duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[5m])\n/\nrate(request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(page_goto_duration_seconds_sum[5m])\n/\nrate(page_goto_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(page_goto_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Any Request Average Duration 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(any_request_duration_seconds_sum[5m])\n/\nrate(any_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(any_request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Any Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "any_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saving hrefs Durante 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(saving_found_hrefs_duration_seconds_sum[5m]))\n/\nsum(rate(saving_found_hrefs_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(saving_found_hrefs_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clean DB Average durante 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(clean_db_duration_seconds_sum[5m])\n/\nrate(clean_db_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads Alive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "targets": [
    { "expr": "threads_alive", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total domains checked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domain_check_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pages marked as same_as",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pages_marked_as_same_as_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total pages released",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pages_released_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average last 5m to return domain_check",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(domain_check_duration_seconds_sum[5m])\n/\nrate(domain_check_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log = INFO",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"miner\"} | detected_level = `INFO`"
    }
   ]
  },
  {
   "title": "LOG != INFO",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"miner\"} | detected_level != `INFO`"
    }
   ]
  }
 ]
}