SET NAMES utf8mb4;

INSERT INTO `settings` (`key`, `value`, `description`) VALUES
  (
    'search_engine',
    JSON_ARRAY('StarterWikipedia'),
    'List of enabled search engines'
  );

INSERT INTO `settings` (`key`, `value`, `description`) VALUES
  (
    'init_terms',
    JSON_ARRAY(
'notícias recentes',
'análise política',
'cenário econômico do brasil',
'inflação no brasil',
'decisões do congresso nacional',
'política internacional',
'crise econômica',
'relatório econômico mensal',
'crítica de filme',
'análise de série',
'lançamentos do cinema',
'biografia de artista',
'bastidores da televisão',
'resenha de álbum musical',
'cultura pop',
'tendências de tecnologia',
'inteligência artificial aplicada',
'segurança da informação',
'desenvolvimento de software',
'computação em nuvem',
'inovação tecnológica',
'transformação digital',
'arquitetura de software',
'engenharia de requisitos',
'testes de software',
'devops',
'observabilidade',
'apis restful',
'documentação de api',
'git',
'github actions',
'docker',
'kubernetes',
'linux',
'sql',
'bancos de dados relacionais',
'nosql',
'engenharia de dados',
'aprendizado de máquina',
'processamento de linguagem natural',
'programação',
'algoritmos e estruturas de dados',
'paradigmas de programação',
'programação orientada a objetos',
'programação funcional',
'compiladores e interpretadores',
'documentação de linguagem',
'referência de linguagem',
'tutorial de linguagem',
'sdk e bibliotecas',
'gerenciamento de pacotes',
'python documentação',
'python biblioteca padrão',
'pip documentação',
'venv python',
'java documentação',
'jvm especificação',
'maven documentação',
'gradle documentação',
'javascript documentação',
'node.js documentação',
'npm documentação',
'typescript documentação',
'c documentação',
'c++ documentação',
'c# documentação',
'.net documentação',
'go documentação',
'go modules documentação',
'rust documentação',
'cargo documentação',
'php documentação',
'composer documentação',
'ruby documentação',
'gem documentação',
'swift documentação',
'kotlin documentação',
'scala documentação',
'perl documentação',
'lua documentação',
'r linguagem documentação',
'julia documentação',
'regex referência',
'http especificação',
'json especificação',
'yaml especificação',
'graphql documentação',
'openapi especificação',
'pesquisa científica',
'artigo científico resumo',
'divulgação científica',
'descobertas recentes na ciência',
'estudo acadêmico',
'inovação em biotecnologia',
'saúde pública',
'prevenção de doenças comuns',
'saúde mental no trabalho',
'alimentação saudável',
'políticas de saúde',
'tratamento para ansiedade',
'educação básica',
'reforma do ensino médio',
'métodos de aprendizagem eficazes',
'ensino superior',
'políticas educacionais atuais',
'educação a distância',
'planejamento financeiro pessoal',
'investimentos para iniciantes',
'renda fixa',
'educação financeira básica',
'controle de gastos mensal',
'imposto de renda pessoa física',
'empreendedorismo',
'gestão empresarial',
'marketing digital',
'análise de mercado',
'comércio eletrônico',
'inovação em modelos de negócio',
'legislação atualizada',
'direitos trabalhistas',
'direito constitucional',
'políticas públicas',
'processo legislativo',
'qualidade de vida urbana',
'turismo destinos',
'gastronomia tradicional',
'desenvolvimento pessoal',
'sustentabilidade no cotidiano',
'campeonato nacional',
'futebol notícias',
'desempenho de atletas',
'história do esporte',
'história contemporânea',
'movimentos culturais',
'literatura análise',
'patrimônio histórico',
'jogos digitais',
'crítica de jogos',
'análise de jogos',
'lançamentos de jogos',
'história dos videogames',
'cultura gamer',
'indústria de games',
'design de jogos',
'game design document',
'narrativa em jogos',
'level design',
'design de sistemas',
'economia de jogos',
'monetização em jogos',
'psicologia do jogador',
'acessibilidade em jogos',
'ux em jogos',
'qa e testes em jogos',
'anti-cheat',
'multiplayer networking',
'netcode',
'servidores de jogos',
'latência e matchmaking',
'renderização em tempo real',
'gráficos 3d fundamentos',
'shaders',
'física em jogos',
'ia em jogos',
'procedural generation',
'unity documentação',
'unreal engine documentação',
'godot documentação',
'steamworks documentação',
'opengl documentação',
'vulkan documentação',
'directx documentação',
'webgl documentação',
'esports',
'streaming de jogos',
'redes sociais tendências',
'influenciadores digitais',
'economia criativa no brasil',
'streaming e indústria cultural',
'comunidades online e comportamento',
'desinformação e checagem de fatos',
'privacidade em redes sociais',
'cultura de memes',
'publicidade em plataformas digitais',
'dados abertos no brasil',
'indicadores econômicos principais',
'metodologia de pesquisa estatística',
'análise de dados',
'visualização de dados',
'modelos preditivos',
'qualidade de dados e validação',
'governança de dados',
'big data',
'ética em ciência de dados',
'esg no brasil',
'governança corporativa',
'relato de sustentabilidade',
'risco climático e finanças',
'responsabilidade social corporativa',
'compliance e integridade',
'investimento sustentável',
'diversidade e inclusão nas empresas',
'cadeia de fornecedores e due diligence',
'métricas esg',
'mudanças climáticas no brasil',
'desmatamento na amazônia',
'biodiversidade brasileira',
'política ambiental',
'licenciamento ambiental',
'crise hídrica e recursos hídricos',
'energia renovável no brasil',
'poluição do ar',
'resíduos sólidos e reciclagem',
'conservação e unidades de proteção',
'segurança pública no brasil',
'violência urbana',
'políticas de segurança pública',
'crime organizado no brasil',
'sistema prisional brasileiro',
'estatísticas de criminalidade',
'policiamento e estratégias',
'direitos humanos e segurança',
'legislação penal atualizada',
'violência doméstica e políticas',
'mercado de trabalho',
'desemprego e indicadores',
'salário mínimo impactos',
'reforma trabalhista análise',
'informalidade no brasil',
'trabalho remoto tendências',
'economia gig e plataformas',
'qualificação profissional',
'negociação coletiva',
'produtividade e salários',
'desigualdade social no brasil',
'pobreza e políticas sociais',
'mobilidade social',
'indicadores sociais',
'demografia brasileira',
'migração interna no brasil',
'violência de gênero',
'raça e desigualdades',
'juventude e políticas públicas',
'envelhecimento populacional no brasil',
'saneamento básico no brasil',
'transporte público e mobilidade urbana',
'obras públicas e investimentos',
'logística e infraestrutura',
'rodovias e concessões',
'ferrovias no brasil',
'portos e comércio exterior',
'aeroportos e aviação civil',
'habitação e déficit habitacional',
'cidades inteligentes',
'energia elétrica no brasil',
'matriz energética brasileira',
'petróleo e gás no brasil',
'preços de combustíveis análise',
'transição energética',
'energia solar e eólica',
'biocombustíveis no brasil',
'eficiência energética',
'segurança energética',
'regulação do setor elétrico',
'agricultura brasileira panorama',
'política agrícola nacional',
'commodities agrícolas preços',
'segurança alimentar no brasil',
'tecnologia no campo',
'crédito rural',
'agricultura familiar',
'exportações do agronegócio',
'impactos climáticos na produção',
'defensivos agrícolas regulação',
'diplomacia brasileira',
'geopolítica',
'conflitos internacionais análise',
'organizações internacionais',
'comércio exterior brasileiro',
'acordos comerciais e impacto',
'brics análise',
'mercados globais panorama',
'sanções internacionais efeitos',
'migração internacional e refúgio',
'política industrial no brasil',
'indústria 4.0 no brasil',
'automação industrial tendências',
'setor automotivo análise',
'indústria de alimentos panorama',
'indústria de base e mineração',
'competitividade industrial',
'cadeias produtivas no brasil',
'exportações industriais',
'desindustrialização debate',
'relatório técnico',
'manual técnico',
'documentação oficial',
'edital público',
'descrição de produto',
'termos e condições de uso',
'política de privacidade',
'página institucional',
'blog pessoal',
'artigo de opinião',
'relato de experiência',
'comentário crítico',
'eleições no brasil',
'partidos políticos brasileiros',
'campanha eleitoral análise',
'reforma política',
'governança e gestão pública',
'ciência política conceitos',
'opinião pública e pesquisas eleitorais',
'polarização política',
'transparência e accountability',
'corrupção e controle institucional',
'coalizões e articulação política',
'agenda do governo federal'
),
    'Initial search terms'
  );
